
package com.Client.RuleBaseClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RuleBaseImplService", targetNamespace = "http://RuleBaseWebservice.Webservice.com/", wsdlLocation = "http://localhost:9998/ws/rulebase?wsdl")
public class RuleBaseImplService
    extends Service
{

    private final static URL RULEBASEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RULEBASEIMPLSERVICE_EXCEPTION;
    private final static QName RULEBASEIMPLSERVICE_QNAME = new QName("http://RuleBaseWebservice.Webservice.com/", "RuleBaseImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/ws/rulebase?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RULEBASEIMPLSERVICE_WSDL_LOCATION = url;
        RULEBASEIMPLSERVICE_EXCEPTION = e;
    }

    public RuleBaseImplService() {
        super(__getWsdlLocation(), RULEBASEIMPLSERVICE_QNAME);
    }

    public RuleBaseImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RULEBASEIMPLSERVICE_QNAME, features);
    }

    public RuleBaseImplService(URL wsdlLocation) {
        super(wsdlLocation, RULEBASEIMPLSERVICE_QNAME);
    }

    public RuleBaseImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RULEBASEIMPLSERVICE_QNAME, features);
    }

    public RuleBaseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleBaseImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RuleBase
     */
    @WebEndpoint(name = "RuleBaseImplPort")
    public RuleBase getRuleBaseImplPort() {
        return super.getPort(new QName("http://RuleBaseWebservice.Webservice.com/", "RuleBaseImplPort"), RuleBase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleBase
     */
    @WebEndpoint(name = "RuleBaseImplPort")
    public RuleBase getRuleBaseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://RuleBaseWebservice.Webservice.com/", "RuleBaseImplPort"), RuleBase.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RULEBASEIMPLSERVICE_EXCEPTION!= null) {
            throw RULEBASEIMPLSERVICE_EXCEPTION;
        }
        return RULEBASEIMPLSERVICE_WSDL_LOCATION;
    }

}
