
package com.Client.WebserviceBankClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankWebserviceImplService", targetNamespace = "http://WebserviceBank.Webservice.com/", wsdlLocation = "http://localhost:9996/ws/webservicebank?wsdl")
public class BankWebserviceImplService
    extends Service
{

    private final static URL BANKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANKWEBSERVICEIMPLSERVICE_QNAME = new QName("http://WebserviceBank.Webservice.com/", "BankWebserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9996/ws/webservicebank?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANKWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BankWebserviceImplService() {
        super(__getWsdlLocation(), BANKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BankWebserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankWebserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKWEBSERVICEIMPLSERVICE_QNAME);
    }

    public BankWebserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankWebserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankWebservice
     */
    @WebEndpoint(name = "BankWebserviceImplPort")
    public BankWebservice getBankWebserviceImplPort() {
        return super.getPort(new QName("http://WebserviceBank.Webservice.com/", "BankWebserviceImplPort"), BankWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankWebservice
     */
    @WebEndpoint(name = "BankWebserviceImplPort")
    public BankWebservice getBankWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebserviceBank.Webservice.com/", "BankWebserviceImplPort"), BankWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANKWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANKWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
