
package com.Client.WebserviceBankClient;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankWebservice", targetNamespace = "http://WebserviceBank.Webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWebservice {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInterestRate", targetNamespace = "http://WebserviceBank.Webservice.com/", className = "com.Client.WebserviceBankClient.GetInterestRate")
    @ResponseWrapper(localName = "getInterestRateResponse", targetNamespace = "http://WebserviceBank.Webservice.com/", className = "com.Client.WebserviceBankClient.GetInterestRateResponse")
    @Action(input = "http://WebserviceBank.Webservice.com/BankWebservice/getInterestRateRequest", output = "http://WebserviceBank.Webservice.com/BankWebservice/getInterestRateResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://WebserviceBank.Webservice.com/BankWebservice/getInterestRate/Fault/IOException")
    })
    public BigDecimal getInterestRate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception
    ;

}
