
package com.Client.MessageClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Message", targetNamespace = "http://LoanRequestWebservice.Webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Message {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.Client.MessageClient.ReplyObject
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loanRequest", targetNamespace = "http://LoanRequestWebservice.Webservice.com/", className = "com.Client.MessageClient.LoanRequest")
    @ResponseWrapper(localName = "loanRequestResponse", targetNamespace = "http://LoanRequestWebservice.Webservice.com/", className = "com.Client.MessageClient.LoanRequestResponse")
    @Action(input = "http://LoanRequestWebservice.Webservice.com/Message/loanRequestRequest", output = "http://LoanRequestWebservice.Webservice.com/Message/loanRequestResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://LoanRequestWebservice.Webservice.com/Message/loanRequest/Fault/IOException")
    })
    public ReplyObject loanRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception
    ;

}
